In [10]:
import numpy as np

arr = np.full((2,5),3.14)

arr


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
import numpy as np

lotto =np.random.choice(np.arange(1,46),size = 6,replace=False)
print(lotto)

[24 36 43 30 25 28]


In [ ]:
arr = np.array([3.14 , "안녕" , 2 , 4 , 3])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.)

['3.14' '안녕' '2' '4' '3']
1
(5,)


In [34]:
import numpy as np


arr = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120],
    [130,140,150,160]
])

# - 첫 번째 행 전체를 출력하시오.
print(arr[0,:])
# - 세 번째 열 전체를 출력하시오.
print(arr[:,2])
# - 마지막 두 행만 추출하시오.
print(arr[2:])

[10 20 30 40]
[ 30  70 110 150]
[[ 90 100 110 120]
 [130 140 150 160]]


In [51]:
import numpy as np
sales = np.array([
12000,
45000,
38000,
15000,
50000
])
#예상 결과

#[45000 38000 50000]
result = sales[sales > 30000]
print(result)




[45000 38000 50000]


In [99]:
#10.학생 평균이 80 이상인 학생만 추출하시오.
import numpy as np
scores = np.array([
 [80,90,70],
 [60,65,50],
 [95,85,90],
 [70,75,80]
])
avg = np.mean(scores,axis = 1)
result = scores[avg >= 80]
print(result)
# 조건

# 행 평균 >= 80
# 예상 결과

# [
#  [80 90 70]
#  [95 85 90]
# ]
# pig

[[80 90 70]
 [95 85 90]]


In [102]:
#11.음수만 추출하시오.

data = np.array([
    -10, 30, -20,
    50, -60, 90
])
result = data[data < 0]
print(result)
#예상 결과

#[-10 -20 -60]

[-10 -20 -60]


In [ ]:
# # #1. 아래가 에러가 나는 이유는?
 
# # a = np.array([
# #                 [1, 2], 
# #                 [3, 4]
# #             ])  # shape: (2, 2)

# # b = np.array([1, 2, 3]) 
# # print(a + b)  # 에러 발생
# # # 차원이 맞지않는다 행과 열이 안맞는다

# 2. 아래의 함수를 예를 들어 설명하시오.
# arr.flatten() # 1차원 배열로 만드는 함수
# 메트릭스 , 텐서 와 같이 2차원 3차원이상 배열들을 1차원 백터로 만들어주는 함수


# 3. 브로드 캐스팅에 대하여 설명하시오.
# 반복문 없이 계산할수있는 넘파이 기술

# 4.아래의 결과를 예측하시오.

# a = np.array([
#     [1],
#     [2],
#     [3]
# ])
# print(a.shape)

# b = np.array([10,20,30])
# print(b.shape)

# print(a + b)
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

# 5. 넘파이 기초 통계량 함수를 예를 들어 간단하게 설명하시오.
# mean max min sum var 등등 

# 6. reshape 시 arr.reshape(-1,4)   -1 의 의미는?
# 행에 단위를 알아서 맞춰주는것
# # 7. 아래의 배열에서 열단위 , 행단위 정렬을 하시오.
# # 2차원 배열 정렬
# arr = np.random.randint(15,size=(3,4))
# print(arr)
# result = np.sort(arr,axis = 0)
# result2 = np.sort(arr,axis = 1)
# 8. 판다스 에서 시리즈 객체와 데이터 프레임 객체를 간단하게 설명하시오.
# 시리즈는 1차원 백터 데이터 프레임은 2차원 매트릭스

[[ 5  9  5  1]
 [ 9  7 13  7]
 [ 1  0 11  3]]
