In [1]:

import numpy as np

# arr = np.array([0, 1, 2, 3, 4])

# print(arr[2]) # 인덱싱
# print(arr[-2]) # 음수 인덱싱
# print(arr[1:4]) # 슬라이싱

arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
])

print(arr.shape)
print(arr[0] [0]) 
print(arr[-1][-1])

#넘파이는 좌표 방식 접근도 지원
print(arr[0,0])


(2, 3)
0
5
0


In [ ]:
# 슬라이싱

arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("원본 배열:", arr)

#인덱스 4부터 끝까지
print(arr[4:])
#인덱스 1부터 3까지 
print(arr[1:4])
#처음부터 끝까지 , 2칸씩 뛰어라
print(arr[::2])




원본 배열: [10 20 30 40 50 60 70]
[50 60 70]
[20 30 40]
[10 30 50 70]
[70 50 30 10]


In [39]:
#2차원 배열 슬라이싱
arr = np.array([
                    [0, 1, 2, 3], 
                    [4, 5, 6, 7]
                ])
print(arr.shape)

#첫번쨰 행 전체
print(arr[0,:])
print(arr[0][:])

# 두번째 행 전체
print(arr[1,:])

# 두번째 열 전체
print(arr[:,1])

# 두번 째 행의 두번째 열부터 끝열까지[5,6,7]
print(arr[1,1:4])
print(arr[1,1:])


(2, 4)
[0 1 2 3]
[0 1 2 3]
[4 5 6 7]
[1 5]
[5 6 7]
[5 6 7]
