In [ ]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [0, 1, 4]
])

# 배열 전체에서 최소값 찾아보기
print(np.min(arr))
print(arr.min())

print(arr.min(axis = 0)) # 열단위 최소값
print(arr.min(axis = 1)) # 행단위 최소값

print(arr.max(axis = 0))
print(arr.max(axis = 1))
print(np.max(arr))

print(arr.sum(axis = 0))
print(arr.sum(axis = 1))

print(np.sum(arr))
print(arr)
print(np.cumsum(arr))

print(arr.cumsum(axis = 1))
print(arr.cumsum(axis = 0))

#

0
0
[0 1 3]
[1 0]
[1 2 4]
[3 4]
4
[1 3 7]
[6 5]
11
[[1 2 3]
 [0 1 4]]
[ 1  3  6  6  7 11]
[[1 3 6]
 [0 1 5]]
[[1 2 3]
 [1 3 7]]


In [ ]:
# 평균/ 표준편차 / 중앙값

# 평균 mean
print(np.mean(arr))
print(arr.mean(axis= 1))
print(arr.mean())

# 표준편차 std
#데이터가 평균으로부터 얼마나 퍼져있는지 측정하는 값
print(np.std(arr))
print(arr.std(axis = 1))

# 분산 var
print(arr.var(axis = 1))

# 중앙값 median
print(np.median(arr))
# 5 중앙값 2.5
print(arr)
print(np.median(arr, axis = 0))

# 분산 / var  / 중앙값 median / mean 


1.8333333333333333
[2.         1.66666667]
1.8333333333333333
1.343709624716425
[0.81649658 1.69967317]
[0.66666667 2.88888889]
1.5
[[1 2 3]
 [0 1 4]]
[0.5 1.5 3.5]
