In [ ]:
# 넘파이 브로드 캐스팅
# 서로 크기가 다른 배열들 간의 연산을 가능하게 해주는 규칙
# 이 기능 덕분에 반복문 없이도 벡터화된 연산을 수행할 수 있어 빠르고 효율적인 계산이 가능.
# 브로드 캐스팅의 원리: 서로의 행렬을 맞추기위해 확장
# 원소가 하나인 배열은 어떤 배열이나 브로드캐스팅이 가능
# 하나의 배열이 1차원 배열인 경우, 브로드캐스팅이 가능

import numpy as np

a = np.array([1,2,3])
b = 2

print(a + b)
# 반복문없이 돌아가는 것

a = np.array([
    [1],
    [2],
    [3]
])

print(a.shape)

b = np.array([10,20,30])
print(b.shape)

print( a + b)




[3 4 5]
(3, 1)
(3,)
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [84]:
# #브로드 캐스팅이 안되는 케이스
# a = np.array([
#                 [1, 2], 
#                 [3, 4]
#             ])  # shape: (2, 2)

# b = np.array([1, 2, 3]) 
# print(a + b)  # 에러 발생
# # 행열 이 안맞음 / 브로드캐스팅안됨 