In [2]:
import numpy as np

arr = np.full((2,5),3.14)

arr


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
import numpy as np

lotto =np.random.choice(np.arange(1,46),size = 6,replace=False)
print(lotto)

[24 36 43 30 25 28]


In [ ]:
arr = np.array([3.14 , "안녕" , 2 , 4 , 3])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.)

['3.14' '안녕' '2' '4' '3']
1
(5,)


In [ ]:
import numpy as np


arr = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120],
    [130,140,150,160]
])

# - 첫 번째 행 전체를 출력하시오.
print(arr[0,:])
# - 세 번째 열 전체를 출력하시오.
print(arr[:,2])
# - 마지막 두 행만 추출하시오.
print(arr[2:])

[10 20 30 40]
[ 30  70 110 150]
[[ 90 100 110 120]
 [130 140 150 160]]


In [ ]:
import numpy as np
sales = np.array([
12000,
45000,
38000,
15000,
50000
])
#예상 결과

#[45000 38000 50000]
result = sales[sales > 30000]
print(result)




[45000 38000 50000]


In [ ]:
#10.학생 평균이 80 이상인 학생만 추출하시오.
import numpy as np
scores = np.array([
 [80,90,70],
 [60,65,50],
 [95,85,90],
 [70,75,80]
])
avg = np.mean(scores,axis = 1)
result = scores[avg >= 80]
print(result)
# 조건

# 행 평균 >= 80
# 예상 결과

# [
#  [80 90 70]
#  [95 85 90]
# ]
# pig

[[80 90 70]
 [95 85 90]]


In [ ]:
#11.음수만 추출하시오.

data = np.array([
    -10, 30, -20,
    50, -60, 90
])
result = data[data < 0]
print(result)
#예상 결과

#[-10 -20 -60]

[-10 -20 -60]


In [ ]:
# # #1. 아래가 에러가 나는 이유는?
 
# # a = np.array([
# #                 [1, 2], 
# #                 [3, 4]
# #             ])  # shape: (2, 2)

# # b = np.array([1, 2, 3]) 
# # print(a + b)  # 에러 발생
# # # 차원이 맞지않는다 행과 열이 안맞는다

# 2. 아래의 함수를 예를 들어 설명하시오.
# arr.flatten() # 1차원 배열로 만드는 함수
# 메트릭스 , 텐서 와 같이 2차원 3차원이상 배열들을 1차원 백터로 만들어주는 함수


# 3. 브로드 캐스팅에 대하여 설명하시오.
# 반복문 없이 계산할수있는 넘파이 기술

# 4.아래의 결과를 예측하시오.

# a = np.array([
#     [1],
#     [2],
#     [3]
# ])
# print(a.shape)

# b = np.array([10,20,30])
# print(b.shape)

# print(a + b)
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

# 5. 넘파이 기초 통계량 함수를 예를 들어 간단하게 설명하시오.
# mean max min sum var 등등 

# 6. reshape 시 arr.reshape(-1,4)   -1 의 의미는?
# 행에 단위를 알아서 맞춰주는것
# # 7. 아래의 배열에서 열단위 , 행단위 정렬을 하시오.
# # 2차원 배열 정렬
# arr = np.random.randint(15,size=(3,4))
# print(arr)
# result = np.sort(arr,axis = 0)
# result2 = np.sort(arr,axis = 1)
# 8. 판다스 에서 시리즈 객체와 데이터 프레임 객체를 간단하게 설명하시오.
# 시리즈는 1차원 백터 데이터 프레임은 2차원 매트릭스

[[ 5  9  5  1]
 [ 9  7 13  7]
 [ 1  0 11  3]]


In [15]:
import numpy as np

arr = np.arange(9)

print(arr)

arr2 = arr.reshape(-1,3)
arr2

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
import pandas as pd

s = pd.Series(
    [95, 88, 76],
    index=["Kim", "Lee", "Park"]
)
# s["choi"] = 92
# print(s)
# 3-1다음 조건을 만족하도록 코드를 작성하세요.

# "Choi" 학생의 점수 92를 추가한다.
# 기존 데이터는 유지한다.


# 3-2다음 작업을 수행하는 코드를 작성하세요.

# "Lee"의 점수를 조회한다.
# 점수가 90점 이상인 학생만 조회한다.
# print(s["Lee"])
# print(s[s >= 90])
# # 3-3 다음 조건을 만족하도록 코드를 작성하세요.

# # "Park"의 점수를 85로 수정한다.
# s["Park"] = 85
# s
# 3-4 다음 조건을 만족하도록 코드를 작성하세요.

# "Lee" 데이터를 삭제한다.
s = s.drop("Lee")
print(s)

# 3- 5 응용 문제

# 최종 Series에서:
print(s.mean())
# 평균 점수를 구하시오.
# 최고 점수를 가진 학생 이름을 구하시오.
print(s.max())
# 점수 기준 내림차순 정렬하시오.
print(s.sort_values(ascending=True))

Kim     95
Park    76
dtype: int64
85.5
95
Park    76
Kim     95
dtype: int64


In [20]:
import pandas as pd

s = pd.Series(
    [10, 20, 30, 40, 50],
    index=["A", "B", "C", "D", "E"]
)

print(s)
print(s["B":"D"])
# print(s.iloc[2])

# print(s.iloc[1:4])


A    10
B    20
C    30
D    40
E    50
dtype: int64
B    20
C    30
D    40
dtype: int64


In [ ]:
import pandas as pd
import numpy as np

data = {
    '이름' : ['유재석', '박명수', '정준하', '노홍철', '정형돈', '하하'],
    '지역' : ['서울', '부산', '부산', '서울', '서울', '서울'],
    '나이' : [19, 23, 20, 25, 18, 21],
    '국어점수' : [86, 90, 80, 65, 50, 60],
    '수학점수' : [86, 100, 66, 70, 40, 80],
    '코딩' : ['Python', 'Java', np.nan, 'Javascript', 'PYTHON', np.nan]
}
df = pd.Ddf["평균"] = df["국어점수"] + df["수학점수"] % 2
print(df)

def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    else:
        return "C"
    
df["등급"] = df["평균"].apply(grade)
print(df)ataFrame(data, index=['1번', '2번', '3번', '4번', '5번', '6번'])
print(df)




     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  서울  19    86    86      Python
2번  박명수  부산  23    90   100        Java
3번  정준하  부산  20    80    66         NaN
4번  노홍철  서울  25    65    70  Javascript
5번  정형돈  서울  18    50    40      PYTHON
6번   하하  서울  21    60    80         NaN
     이름  지역  나이  국어점수  수학점수          코딩  평균
1번  유재석  서울  19    86    86      Python  86
2번  박명수  부산  23    90   100        Java  90
3번  정준하  부산  20    80    66         NaN  80
4번  노홍철  서울  25    65    70  Javascript  65
5번  정형돈  서울  18    50    40      PYTHON  50
6번   하하  서울  21    60    80         NaN  60
     이름  지역  나이  국어점수  수학점수          코딩  평균 등급
1번  유재석  서울  19    86    86      Python  86  B
2번  박명수  부산  23    90   100        Java  90  A
3번  정준하  부산  20    80    66         NaN  80  B
4번  노홍철  서울  25    65    70  Javascript  65  C
5번  정형돈  서울  18    50    40      PYTHON  50  C
6번   하하  서울  21    60    80         NaN  60  C


In [29]:
import pandas as pd
import numpy as np

data = [70, 71, 72, 73, 74, 75, 76, 77, 78, 150]
s = pd.Series(data)
s.describe()

count     10.000000
mean      81.600000
std       24.171609
min       70.000000
25%       72.250000
50%       74.500000
75%       76.750000
max      150.000000
dtype: float64

In [45]:
import pandas as pd
import numpy as np

data = {
    '이름' : ['유재석', '박명수', '정준하', '노홍철', '정형돈', '하하'],
    '지역' : ['서울', '부산', '부산', '서울', '서울', '서울'],
    '나이' : [19, 23, 20, 25, 18, 21],
    '국어점수' : [86, 90, 80, 65, 50, 60],
    '수학점수' : [86, 100, 66, 70, 40, 80],
    '코딩' : ['Python', 'Java', np.nan, 'Javascript', 'PYTHON', np.nan]
}
df = pd.DataFrame(data)
print(df)

# print(df[(df["지역"] == "부산") & (df["나이"] >= 20)])

# print(df.iloc[0:2 , 3:5])
# print(df.iloc[[0,1] , [3,4]])
# print(df.describe()) 

print(df['국어점수'].describe())
print(df['국어점수'].count())
print(df['국어점수'].min())
print(df['국어점수'].max())

print(df['국어점수'].sum())

    이름  지역  나이  국어점수  수학점수          코딩
0  유재석  서울  19    86    86      Python
1  박명수  부산  23    90   100        Java
2  정준하  부산  20    80    66         NaN
3  노홍철  서울  25    65    70  Javascript
4  정형돈  서울  18    50    40      PYTHON
5   하하  서울  21    60    80         NaN
count     6.000000
mean     71.833333
std      15.879757
min      50.000000
25%      61.250000
50%      72.500000
75%      84.500000
max      90.000000
Name: 국어점수, dtype: float64
6
50
90
431


In [53]:
import pandas as pd

data = [60, 62, 63, 64, 65, 66, 67, 68, 69, 100]

s = pd.Series(data)
print(s)
print("평균:", s.mean())
print("중앙값:", s.median())

0     60
1     62
2     63
3     64
4     65
5     66
6     67
7     68
8     69
9    100
dtype: int64
평균: 68.4
중앙값: 65.5
